//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "DeviceInfo.xaml.h"

void ::MW_CPP_UWP_SampleApp::DeviceInfo::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///DeviceInfo.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::MW_CPP_UWP_SampleApp::DeviceInfo::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->LedButtons = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 2:
            {
                ::Windows::UI::Xaml::Controls::Button^ element2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element2))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MW_CPP_UWP_SampleApp::DeviceInfo::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceInfo::ledOff);
            }
            break;
        case 3:
            {
                this->HapticButtons = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 4:
            {
                this->MainView = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 5:
            {
                this->sensorsSwitch = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 6:
            {
                this->outputListView = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(__target);
            }
            break;
        case 7:
            {
                this->swAcc = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->swAcc))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MW_CPP_UWP_SampleApp::DeviceInfo::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceInfo::toggleAccelerationSampling);
            }
            break;
        case 8:
            {
                ::Windows::UI::Xaml::Controls::ToggleSwitch^ element8 = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(element8))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MW_CPP_UWP_SampleApp::DeviceInfo::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceInfo::toggleAmbientLightSampling);
            }
            break;
        case 9:
            {
                ::Windows::UI::Xaml::Controls::ToggleSwitch^ element9 = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(element9))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MW_CPP_UWP_SampleApp::DeviceInfo::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceInfo::toggleBarometerSampling);
            }
            break;
        case 10:
            {
                this->swGyro = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->swGyro))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MW_CPP_UWP_SampleApp::DeviceInfo::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceInfo::toggleGyroSampling);
            }
            break;
        case 11:
            {
                ::Windows::UI::Xaml::Controls::ToggleSwitch^ element11 = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(element11))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MW_CPP_UWP_SampleApp::DeviceInfo::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceInfo::toggleSwitchSampling);
            }
            break;
        case 12:
            {
                ::Windows::UI::Xaml::Controls::ToggleSwitch^ element12 = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(element12))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MW_CPP_UWP_SampleApp::DeviceInfo::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceInfo::toggleGPIO);
            }
            break;
        case 13:
            {
                ::Windows::UI::Xaml::Controls::Button^ element13 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element13))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MW_CPP_UWP_SampleApp::DeviceInfo::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceInfo::startMotor);
            }
            break;
        case 14:
            {
                ::Windows::UI::Xaml::Controls::Button^ element14 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element14))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MW_CPP_UWP_SampleApp::DeviceInfo::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceInfo::startBuzzer);
            }
            break;
        case 15:
            {
                ::Windows::UI::Xaml::Controls::Button^ element15 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element15))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MW_CPP_UWP_SampleApp::DeviceInfo::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceInfo::ledRedOn);
            }
            break;
        case 16:
            {
                ::Windows::UI::Xaml::Controls::Button^ element16 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element16))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MW_CPP_UWP_SampleApp::DeviceInfo::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceInfo::ledGreenOn);
            }
            break;
        case 17:
            {
                ::Windows::UI::Xaml::Controls::Button^ element17 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element17))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MW_CPP_UWP_SampleApp::DeviceInfo::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceInfo::ledBlueOn);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::MW_CPP_UWP_SampleApp::DeviceInfo::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


